// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfaqNLI_VssDzaMDHRSSvvfa2HNnuIXqA',
    appId: '1:616112986042:web:82e69222017e09583e2f83',
    messagingSenderId: '616112986042',
    projectId: 'investme-a3e22',
    authDomain: 'investme-a3e22.firebaseapp.com',
    storageBucket: 'investme-a3e22.firebasestorage.app',
    measurementId: 'G-WTJPMM0YHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiJyW_jjDw15_vVKyXQ8iV8pAMqxUXFHg',
    appId: '1:616112986042:android:93bf940f22b5be5a3e2f83',
    messagingSenderId: '616112986042',
    projectId: 'investme-a3e22',
    storageBucket: 'investme-a3e22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvAHYDBSdVk7z2h2KaFgj2-3e9NmUXOpI',
    appId: '1:616112986042:ios:e64e656428affea83e2f83',
    messagingSenderId: '616112986042',
    projectId: 'investme-a3e22',
    storageBucket: 'investme-a3e22.firebasestorage.app',
    iosBundleId: 'com.example.invesme',
  );
}
